CREATE TABLE IF NOT EXISTS logs (
    id SERIAL PRIMARY KEY,
    estacion_id INT NOT NULL,
    temperatura FLOAT NOT NULL,
    humedad FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
